name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle
        run: |
          gradle build
          echo VERSION=$(gradle -q properties | findstr version: | cut -d ' ' -f 2) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          tag_name: v${{ env.VERSION }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}