name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:

      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: .NET Build
        run: |
          echo VERSION=$(echo 3.0.1) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          dotnet publish
          iscc setup.iss

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/CustomDiscordRPC.exe
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}