name: Build
on: workflow_dispatch
jobs:
    
    build:
        name: Build
        runs-on: windows-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.0.x

            - name: Build
              run: dotnet publish /p:PublishProfile=Publish

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                files: CustomDiscordRPC/bin/Publish/*.exe
                tag_name: 3.2.2
                fail_on_unmatched_files: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}